---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry-k8s
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
        "spiffe.io/spiffe-id": "true"
    spec:
      serviceAccountName: registry-k8s-sa
      containers:
        - image: ghcr.io/networkservicemesh/ci/cmd-registry-k8s:8a414be
          env:
            - name: SPIFFE_ENDPOINT_SOCKET
              value: unix:///spiffe-workload-api/agent.sock
            - name: REGISTRY_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REGISTRY_K8S_LOG_LEVEL
              value: TRACE
            - name: REGISTRY_K8S_LISTEN_ON
              value: tcp://:5002
            - name: REGISTRY_K8S_PROXY_REGISTRY_URL
              value: nsmgr-proxy:5004
          imagePullPolicy: IfNotPresent
          name: registry
          ports:
            - containerPort: 5002
              hostPort: 5002
          volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
          resources:
            requests:
              cpu: 100m
            limits:
              memory: 40Mi
              cpu: 200m
      volumes:
        - name: spiffe-workload-api
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
